[package]
name = "kioto"
version = "2.5.2"
compiler = "mire"
abi = 1
language = "mire avenys v3.24.27"

[features]
compat-v2 = []  # enables core/compat shim for v2 API
minimal-runtime = []  # disables libsodium/openssl deps, only core PAL
