[project]
name = "kioto"
version = "3.0.0"
description = "Kioto is the Avenys/mire standard library"
entry = "src/mod.mr"

[build]
compiler = "mire"
profile = "debug"
opt-level = 0
artifact = "shared"
runtime = "minimal"
target = "x86_64-unknown-linux-gnu"
panic = "abort"
incremental = true
debug-info = true

[paths]
sources = "src"
tests = "tests"
output = "bin"
cache = "bin/.cache"

[dependencies]
mire = { path = "~/.owl/libs/mire" }
kioto = { path = "." }

[security]
mode = "strict"
externs = ["pal_*", "rt_list_*", "rt_lists_*", "rt_vecs_*", "rt_dict*", "rt_map*", "rt_string*", "rt_i64_to_string", "rt_f64_to_string", "rt_bool_to_string", "rt_managed_*"]
extern-libs = ["c"]
macros = ["assert", "assert_eq", "assert_ne", "dbg", "trace_i64"]

[exports]
strings = "modules/strings"
time    = "modules/time"
fs      = "modules/fs"
env     = "modules/env"
proc    = "modules/proc"
async   = "modules/async"
mem     = "modules/mem"
cpu     = "modules/cpu"
math    = "modules/math"
net     = "modules/net"
log     = "modules/log"
cli     = "modules/cli"
crypto  = "modules/crypto"
