[package]
name = "kioto"
version = "2.4.4"
archive = "kioto-2.4.4.tar.zst"
sha256 = "5b1c0d3d90afdd731818b5dced7e9e2369eb11e81eb7275fda47c550255f09bf"
public-key = "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUNvd0JRWURLMlZ3QXlFQVRxZmVPRXZmczdTbW5BLzR5OS8yQ0dCVmhpUk8wNkczSTl0dXdxeTV2Rjg9Ci0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQo="
signature = "ZaN2CkmznM4AKivmn24uzvQKBgEBipq5GiSttHW4Aw4mhR+MrHgcZ/3I+UjwM/aShZrbGJnEvjk685RS+mLTBw=="
