[package]
name = "kioto"
version = "2.3.0"
archive = "kioto-2.3.0.tar.zst"
sha256 = "380b676ab45ceba79b5cb3eea15d9c4d6ba6ab43a7107321b64ed1eb5b3806b8"
public-key = "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUNvd0JRWURLMlZ3QXlFQVRxZmVPRXZmczdTbW5BLzR5OS8yQ0dCVmhpUk8wNkczSTl0dXdxeTV2Rjg9Ci0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQo="
signature = "sI2pPQKWPZ9jw0ThaEZKk6/+JL4Nh8yFX9fQlooXJkJAZDG+MCs0IO5AN21WZO760/HuRtif+TplwZFXhGwBBA=="
