[project]
name = "net"
entry = "mod.mire"

[build]
compiler = "mire"
profile = "debug"
opt-level = 0
artifact = "shared"
runtime = "minimal"
target = "x86_64-unknown-linux-gnu"
panic = "abort"
incremental = true
debug-info = true

[paths]
sources = "."
tests = "tests"
output = "bin"
cache = "bin/.cache"
source = "."
test = "tests"
bin = "bin"
generated = "bin/generated"

[exports]
_externs = "_externs.mire"
["owl@lock"]
version = "3"
