[project]
name = "math"
entry = "mod.mire"

[exports]
_externs = "_externs.mire"
constants = "constants"
number_theoretic = "number_theoretic"
float = "float"
float_manip = "float_manip"
power = "power"
sum = "sum"
angle = "angle"
trig = "trig"
hyperbolic = "hyperbolic"
special = "special"
complex = "complex.mire"
decimal = "decimal.mire"
random = "random.mire"